class measurmentlistcustom {
  dynamic
      MeasurementMode,
      m1,
      m2,
      m3,
      ManualMBNo,
      m4,
      EMBWorkId,
      m5,
      RABillMeasurementid,
      m6,
      m7,
      UnitSymbol,
      m8,
      workName,
      Unit,
      m9,
      ItemId,
      m10,
      ManualMBReference,
      number,
      total,
      MeasurementDate,
      ItemNo;

  measurmentlistcustom(
      {this.MeasurementMode,
      this.m1,
      this.m2,
      this.m3,
      this.ManualMBNo,
      this.m4,
      this.EMBWorkId,
      this.m5,
      this.RABillMeasurementid,
      this.m6,
      this.m7,
      this.UnitSymbol,
      this.m8,
      this.workName,
      this.Unit,
      this.m9,
      this.ItemId,
      this.m10,
      this.ManualMBReference,
      this.number,
      this.total,
      this.MeasurementDate,
      this.ItemNo});

  factory measurmentlistcustom.fromJson(Map<String, dynamic> json) {
      return measurmentlistcustom(
          MeasurementMode: json['MeasurementMode'],
          m1: json['m1'],
          m2: json['m2'],
          m3: json['m3'],
          ManualMBNo: json['ManualMBNo'],
          m4: json['m4'],
          EMBWorkId: json['EMBWorkId'],
          m5: json['m5'],
          RABillMeasurementid: json['RABillMeasurementid'],
          m6: json['m6'],
          m7: json['m7'],
          UnitSymbol: json['UnitSymbol'],
          m8: json['m8'],
          workName: json['workName'],
          Unit: json['Unit'],
          m9: json['m9'],
          ItemId: json['ItemId'],
          m10: json['m10'],
          ManualMBReference: json['ManualMBReference'],
          number: json['number'],
          total: json['total'],
          MeasurementDate: json['MeasurementDate'],
          ItemNo: json['ItemNo'],

      );
  }
}
